[package]
name = "bevy_track_asset"
version = "0.2.1"
edition = "2024"
resolver = "2"
license = "MIT OR Apache-2.0"
authors = ["Jacob Bergholtz <cuppachino.dev@gmail.com>"]
description = "Propagate asset changes to dependent components and resources in Bevy."
documentation = "https://docs.rs/bevy_track_asset"
repository = "https://github.com/cuppachino/pixel_perfect"
readme = "README.md"
keywords = ["bevy", "gamedev", "asset", "change", "reload"]
categories = ["game-development", "rust-patterns"]

[dependencies]
bevy_app = { workspace = true, optional = true }
bevy_asset = { workspace = true }
bevy_ecs = { workspace = true }
bevy_log = { workspace = true, optional = true }
bevy_platform = { workspace = true }

[features]
default = ["bevy_app", "bevy_log"]
bevy_app = ["dep:bevy_app"]
bevy_log = ["dep:bevy_log"]

[dev-dependencies]
bevy = { version = "0.18.1", features = ["file_watcher"] }

[[example]]
name = "auto_param"
required-features = ["bevy_app"]
