[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2024"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

[profile.release]
# Compile the entire crate as one unit.
# Slows compile times, marginal improvements.
codegen-units = 1
# Do a second optimization pass over the entire program, including dependencies.
# Slows compile times, marginal improvements.
lto = "thin"

[workspace.dependencies]
# Packages
font = { package = "raster_font", path = "crates/raster_font" }
bevy_track_asset = { path = "crates/bevy_track_asset" }
# General Dependencies
serde = { version = "1.0.228", features = ["derive"] }
toml = { version = "1.1.0" }
# Bevy Core
bevy_app = { version = "0.18.1" }
bevy_color = { version = "0.18.1" }
bevy_ecs = { version = "0.18.1" }
bevy_asset = { version = "0.18.1" }
bevy_derive = { version = "0.18.1" }
bevy_log = { version = "0.18.1" }
bevy_math = { version = "0.18.1", default-features = false, features = ["std"] }
bevy_platform = { version = "0.18.1" }
bevy_reflect = { version = "0.18.1" }
# Bevy UI
bevy_ui = { version = "0.18.1" }
# Bevy 2D
bevy_sprite = { version = "0.18.1" }
# Bevy Images
bevy_image = { version = "0.18.1" }
bevy_render = { version = "0.18.1" }
# Bevy Optional
atomicow = { version = "1.1.0" }
